name: Dart

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '2.8.1' # Specify your desired Flutter version

    - name: Flutter Pub Get
      run: flutter pub get

    - name: Run Tests
      run: flutter test
